---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: csns
  labels:
    app: cs
    name: cs-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-retain
